Add `remix-i18next` to dependencies to bundle
To avoid the error:

> SyntaxError: Named export 'RemixI18Next' not found.
> The requested module 'remix-i18next' is a CommonJS module,
> ...

Which is caused by a bug in the way the library is exposing this hybrid
package. See https://github.com/sergiodxa/remix-i18next/issues/143